#base-no GPU bits
services:
  postgres-source:
    image: postgres:16-alpine
    container_name: insurance-source-db
    environment:
      POSTGRES_USER: insurance_user
      POSTGRES_PASSWORD: insurance_pw
      POSTGRES_DB: insurance_db
    command: >
      postgres -c wal_level=logical
               -c max_wal_senders=4
               -c max_replication_slots=4
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-llm
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  pgdata:
  ollama_data: